#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 21 16:59:28 CET 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 20e00f933c2f411e9193df39f8f25cac --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot counter_bench_behav xil_defaultlib.counter_bench -log elaborate.log"
xelab -wto 20e00f933c2f411e9193df39f8f25cac --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot counter_bench_behav xil_defaultlib.counter_bench -log elaborate.log

