set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUSLED_O}]

set_property PACKAGE_PIN P1 [get_ports {LEDS_O[0]}]
set_property PACKAGE_PIN N2 [get_ports {LEDS_O[1]}]
set_property PACKAGE_PIN N1 [get_ports {LEDS_O[2]}]
set_property PACKAGE_PIN M2 [get_ports {LEDS_O[3]}]
set_property PACKAGE_PIN P3 [get_ports {LEDS_O[4]}]
set_property PACKAGE_PIN N3 [get_ports {LEDS_O[5]}]
set_property PACKAGE_PIN M1 [get_ports {LEDS_O[6]}]
set_property PACKAGE_PIN A17 [get_ports {LEDS_O[7]}]
set_property PACKAGE_PIN C16 [get_ports {STATUSLED_O}]

set_property IOSTANDARD LVCMOS33 [get_ports CLK_I]
set_property PACKAGE_PIN A16 [get_ports CLK_I]
create_clock -period 40.00 [get_ports CLK_I]

set_property IOSTANDARD LVCMOS33 [get_ports RX_I]
set_property IOSTANDARD LVCMOS33 [get_ports TX_O]
set_property PACKAGE_PIN J17 [get_ports RX_I]
set_property PACKAGE_PIN J18 [get_ports TX_O]