#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Mar 14 19:47:30 CET 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e2b3378a95df42fcaa3a24603340ee94 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot mem_cntr_behav xil_defaultlib.mem_cntr -log elaborate.log"
xelab -wto e2b3378a95df42fcaa3a24603340ee94 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot mem_cntr_behav xil_defaultlib.mem_cntr -log elaborate.log

