webtalk_init -webtalk_dir /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/Lab3/Lab3.sim/sim_1/impl/timing/xsim/xsim.dir/counter_bench_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 22 09:43:02 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6f04da1f-521c-408b-9d4d-7c3a93f9c211" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "20e00f933c2f411e9193df39f8f25cac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2193.762 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "337 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "85 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2851" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "123" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "330404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2438720687 -regid "" -xml /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/Lab3/Lab3.sim/sim_1/impl/timing/xsim/xsim.dir/counter_bench_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/Lab3/Lab3.sim/sim_1/impl/timing/xsim/xsim.dir/counter_bench_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/Lab3/Lab3.sim/sim_1/impl/timing/xsim/xsim.dir/counter_bench_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
