#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Mar 04 17:53:04 CET 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d75e99258727490aa65a2d6a07ccb0f0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot uart_rx_behav xil_defaultlib.uart_rx -log elaborate.log"
xelab -wto d75e99258727490aa65a2d6a07ccb0f0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot uart_rx_behav xil_defaultlib.uart_rx -log elaborate.log

