webtalk_init -webtalk_dir /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/smoothening_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 17 10:53:18 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6f04da1f-521c-408b-9d4d-7c3a93f9c211" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "604ddc9e5e814cbd8e128beed78a136a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3306.291 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2400 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "134004_KB" -context "xsim\\usage"
webtalk_transmit -clientid 694030418 -regid "" -xml /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/smoothening_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/smoothening_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sebastian/Desktop/Git/AdvancedProgrammableElectronics/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/smoothening_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
