set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports U13_I]
set_property IOSTANDARD LVCMOS33 [get_ports U10_IO]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_O]

set_property PACKAGE_PIN M1 [get_ports {LED_O[6]}]
set_property PACKAGE_PIN N3 [get_ports {LED_O[5]}]
set_property PACKAGE_PIN P3 [get_ports {LED_O[4]}]
set_property PACKAGE_PIN M2 [get_ports {LED_O[3]}]
set_property PACKAGE_PIN N1 [get_ports {LED_O[2]}]
set_property PACKAGE_PIN N2 [get_ports {LED_O[1]}]
set_property PACKAGE_PIN P1 [get_ports {LED_O[0]}]
set_property PACKAGE_PIN L3 [get_ports U10_IO]
set_property PACKAGE_PIN M3 [get_ports CLK_O]
set_property PACKAGE_PIN A16 [get_ports U13_I]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

create_clock -period 400000000.000 -name U13_I -waveform {0.000 200000000.000} [get_ports U13_I]
set_output_delay -clock [get_clocks U13_I] -clock_fall -min -add_delay 0.100 [get_ports {LED_O[*]}]
set_output_delay -clock [get_clocks U13_I] -clock_fall -max -add_delay 0.100 [get_ports {LED_O[*]}]