#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 21 21:28:56 CET 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim counter_bench_time_impl -key {Post-Implementation:sim_1:Timing:counter_bench} -tclbatch counter_bench.tcl -log simulate.log"
xsim counter_bench_time_impl -key {Post-Implementation:sim_1:Timing:counter_bench} -tclbatch counter_bench.tcl -log simulate.log

